### ISSUE TITLE
Consider using borsh instead of bincode for serialization

### ISSUE THREAD

**Issue by nchashch** [LayerTwo-Labs/thunder-rust#6]
Because in thunder `bincode` is used to serialize structs before hashing them, it might be better to use [`borsh`](https://borsh.io/), which is specifically designed for this purpose.

But we will need to figure out how to use `borsh` instead of `bincode` with heed, because there is no analogue for `SerdeBincode` type for `borsh`.

**Comment by Ash-L2L** [comment]
`borsh` is already used for canonical encoding when hashing. `bincode` is acceptable for storage and networking - canonical serialization is not necessary for either of these purposes.

Upon review, I did find that `bincode` was used when checking block body size, which has been fixed in 3f31b5697e488857d5cab43a741539571eba2341.

For reference, it is possible to use `borsh` as a custom codec for `heed`:
```rust
struct Borsh<T>(std::marker::PhantomData<T>);

impl<'a, T> heed::BytesDecode<'a> for Borsh<T> where T: borsh::BorshDeserialize + 'a {
    type DItem = T;

    fn bytes_decode(bytes: &'a [u8]) -> Result<Self::DItem, heed::BoxedError> {
        let res = borsh::from_slice(bytes)?;
        Ok(res)
    }
}

impl<'a, T> heed::BytesEncode<'a> for Borsh<T> where T: borsh::BorshSerialize + 'a {
    type EItem = T;

    fn bytes_encode(item: &'a Self::EItem) -> Result<std::borrow::Cow<'a, [u8]>, heed::BoxedError> {
        let bytes = borsh::to_vec(item)?;
        Ok(std::borrow::Cow::Owned(bytes))
    }
}
```
